apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-server
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${var.cluster_name}-parameter-store-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  labels:
    app: backend-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-server
  template:
    metadata:
      labels:
        app: backend-server
    spec:
      serviceAccountName: backend-server
      containers:
      - name: backend-server
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/backend-server:${TAG}
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - secretRef:
            name: rds-credentials
        livenessProbe:
          httpGet:
            path: /actuator/health   # Liveness Probe는 서버가 살아있는지 체크
            port: 8080
          initialDelaySeconds: 60  
          periodSeconds: 10
          failureThreshold: 5      
        
        readinessProbe:
          httpGet:
            path: /actuator/health    # Readiness Probe도 동일한 엔드포인트 사용 (임시)
            port: 8080
          initialDelaySeconds: 30  
          periodSeconds: 10
          failureThreshold: 3
