# backend-server/k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ingress-nginx
  labels:
    app: backend-server
spec:
  selector:
    app: backend-server
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer  # 외부 접근 해야 돼서 로드 밸런서로 수정
